#!/usr/bin/env bash
set -e
go build -o dev/ ./...

GOOS=js GOARCH=wasm go build -o dev/ ./web
base64 -w 0 dev/web >dev/web.base64
cp -f "$(go env GOROOT)/misc/wasm/wasm_exec.js" dev/
gomplate -f web/index.html.templ -o dev/index.html
