#!/usr/bin/env bash
set -e
mkdir -p dev/cli
mkdir -p dev/web

go build -o dev/cli ./...

GOOS=js GOARCH=wasm go build -o dev/web ./web
base64 -w 0 dev/web/web >dev/web/derk.base64
cp -f "$(go env GOROOT)/lib/wasm/wasm_exec.js" dev/web
cp web/index.html.templ dev/web
cd dev/web
gomplate -f index.html.templ -o index.html
